package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"unicode"
)

type bindRule struct {
	Owner  string
	Action string
	Intent string
	Set    map[string]string
}

type intentTypeMeta struct {
	Fields map[string]string
}

type enumValueMeta struct {
	ConstName string
	Literal   string
}

type parsedRule struct {
	Rule bindRule
	Errs []error
}

var (
	ownerSegmentPattern = regexp.MustCompile(`^[a-z0-9_]+$`)
	actionPattern       = regexp.MustCompile(`^[a-z0-9_]+$`)
)

func main() {
	repoRoot, err := findRepoRoot()
	if err != nil {
		fmt.Fprintf(os.Stderr, "find repo root: %v\n", err)
		os.Exit(1)
	}

	intents, err := collectIntentTypeMeta(filepath.Join(repoRoot, "internal/ui/intents"))
	if err != nil {
		fmt.Fprintf(os.Stderr, "collect intent metadata: %v\n", err)
		os.Exit(1)
	}
	enums, err := collectEnumTypeMeta(filepath.Join(repoRoot, "internal/ui/intents"))
	if err != nil {
		fmt.Fprintf(os.Stderr, "collect enum metadata: %v\n", err)
		os.Exit(1)
	}

	rules, err := collectBindRules(filepath.Join(repoRoot, "internal/ui/intents"))
	if err != nil {
		fmt.Fprintf(os.Stderr, "collect bind rules: %v\n", err)
		os.Exit(1)
	}

	if err := validateRules(rules, intents, enums); err != nil {
		fmt.Fprintf(os.Stderr, "validate bind rules: %v\n", err)
		os.Exit(1)
	}
	actionIDs := deriveActionIDs(rules)

	actionArgSchemas, actionRequiredArgs, err := deriveActionArgSchemas(rules, intents, enums)
	if err != nil {
		fmt.Fprintf(os.Stderr, "derive action arg schemas: %v\n", err)
		os.Exit(1)
	}
	actionOwners := deriveActionOwners(rules)
	if err := validateActionMetadata(actionIDs, actionOwners); err != nil {
		fmt.Fprintf(os.Stderr, "validate action metadata: %v\n", err)
		os.Exit(1)
	}

	src, err := generateCatalogSource(rules, intents, enums)
	if err != nil {
		fmt.Fprintf(os.Stderr, "generate catalog: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(filepath.Join(repoRoot, "internal/ui/actions/catalog_gen.go"), src, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write generated file: %v\n", err)
		os.Exit(1)
	}

	meta, err := generateActionMetaSource(actionArgSchemas, actionRequiredArgs, actionOwners)
	if err != nil {
		fmt.Fprintf(os.Stderr, "generate action meta: %v\n", err)
		os.Exit(1)
	}
	actionMetaDir := filepath.Join(repoRoot, "internal/ui/actionmeta")
	if err := os.MkdirAll(actionMetaDir, 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir actionmeta: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(filepath.Join(actionMetaDir, "builtins_gen.go"), meta, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write action meta file: %v\n", err)
		os.Exit(1)
	}

	luaTypes, err := generateLuaTypesSource(actionIDs, actionArgSchemas, actionRequiredArgs, actionOwners)
	if err != nil {
		fmt.Fprintf(os.Stderr, "generate lua types: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(filepath.Join(repoRoot, "internal/config/default/types.lua"), luaTypes, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write types.lua: %v\n", err)
		os.Exit(1)
	}
}

func findRepoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", errors.New("go.mod not found in current directory or parents")
		}
		dir = parent
	}
}

func generateCatalogSource(rules []bindRule, intents map[string]intentTypeMeta, enums map[string][]enumValueMeta) ([]byte, error) {
	owners := uniqueOwners(rules)
	revisionsOwners := revisionsOwnerList(owners)
	ownerRules := rulesByOwner(rules)
	useActionArgs := rulesUseActionArgs(rules)

	var b bytes.Buffer
	b.WriteString("// Code generated by cmd/genactions; DO NOT EDIT.\n")
	b.WriteString("package actions\n\n")
	b.WriteString("import (\n")
	b.WriteString("\tkeybindings \"github.com/idursun/jjui/internal/ui/bindings\"\n")
	b.WriteString("\t\"github.com/idursun/jjui/internal/ui/intents\"\n")
	if useActionArgs {
		b.WriteString("\t\"github.com/idursun/jjui/internal/ui/actionargs\"\n")
	}
	b.WriteString(")\n\n")

	b.WriteString("const (\n")
	for _, owner := range owners {
		b.WriteString(fmt.Sprintf("\t%s = %q\n", ownerConst(owner), owner))
	}
	b.WriteString(")\n\n")

	b.WriteString("func IsRevisionsOwner(owner string) bool {\n")
	b.WriteString("\tswitch owner {\n")
	if len(revisionsOwners) > 0 {
		b.WriteString("\tcase ")
		for i, owner := range revisionsOwners {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(ownerConst(owner))
		}
		b.WriteString(":\n")
		b.WriteString("\t\treturn true\n")
	}
	b.WriteString("\tdefault:\n")
	b.WriteString("\t\treturn false\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")

	b.WriteString("func ResolveIntent(owner string, action keybindings.Action, args map[string]any) (intents.Intent, bool) {\n")
	b.WriteString("\tswitch owner {\n")
	for _, owner := range owners {
		b.WriteString(fmt.Sprintf("\tcase %s:\n", ownerConst(owner)))
		b.WriteString("\t\tswitch action {\n")
		for _, r := range ownerRules[owner] {
			b.WriteString(fmt.Sprintf("\t\tcase keybindings.Action(%q):\n\t\t\treturn %s, true\n", canonicalActionID(owner, r.Action), buildIntentExpr(r, intents, enums)))
		}
		b.WriteString("\t\t}\n")
	}
	b.WriteString("\t}\n")
	b.WriteString("\treturn nil, false\n")
	b.WriteString("}\n\n")

	for _, enumType := range sortedEnumTypesUsedByRules(rules, intents, enums) {
		b.WriteString(fmt.Sprintf("func enumArg%s(args map[string]any, name string) intents.%s {\n", toCamel(enumType), enumType))
		b.WriteString(fmt.Sprintf("\tvar zero intents.%s\n", enumType))
		b.WriteString("\tif args == nil {\n\t\treturn zero\n\t}\n")
		b.WriteString("\tv, ok := args[name]\n\tif !ok {\n\t\treturn zero\n\t}\n")
		b.WriteString("\ts, ok := v.(string)\n\tif !ok {\n\t\treturn zero\n\t}\n")
		b.WriteString("\tswitch s {\n")
		for _, val := range enums[enumType] {
			b.WriteString(fmt.Sprintf("\tcase %q:\n\t\treturn intents.%s\n", val.Literal, val.ConstName))
		}
		b.WriteString("\tdefault:\n\t\treturn zero\n\t}\n")
		b.WriteString("}\n\n")
	}

	src, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w\n%s", err, b.String())
	}
	return src, nil
}

func generateActionMetaSource(actionArgSchemas map[string]map[string]string, actionRequiredArgs map[string][]string, actionOwners map[string][]string) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by cmd/genactions; DO NOT EDIT.\n")
	b.WriteString("package actionmeta\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"fmt\"\n")
	b.WriteString("\t\"sort\"\n")
	b.WriteString("\t\"strings\"\n")
	b.WriteString(")\n\n")

	b.WriteString("var builtInActionOwners = map[string][]string{\n")
	ownerActionNames := make([]string, 0, len(actionOwners))
	for action := range actionOwners {
		ownerActionNames = append(ownerActionNames, action)
	}
	sort.Strings(ownerActionNames)
	for _, action := range ownerActionNames {
		b.WriteString(fmt.Sprintf("\t%q: {", action))
		for i, owner := range actionOwners[action] {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(fmt.Sprintf("%q", owner))
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n\n")

	b.WriteString("var builtInActionArgSchemas = map[string]map[string]string{\n")
	actionNames := make([]string, 0, len(actionArgSchemas))
	for action := range actionArgSchemas {
		actionNames = append(actionNames, action)
	}
	sort.Strings(actionNames)
	for _, action := range actionNames {
		schema := actionArgSchemas[action]
		b.WriteString(fmt.Sprintf("\t%q: {\n", action))
		argNames := make([]string, 0, len(schema))
		for arg := range schema {
			argNames = append(argNames, arg)
		}
		sort.Strings(argNames)
		for _, arg := range argNames {
			b.WriteString(fmt.Sprintf("\t\t%q: %q,\n", arg, schema[arg]))
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n\n")

	b.WriteString("var builtInActionRequiredArgs = map[string][]string{\n")
	requiredActionNames := make([]string, 0, len(actionRequiredArgs))
	for action := range actionRequiredArgs {
		requiredActionNames = append(requiredActionNames, action)
	}
	sort.Strings(requiredActionNames)
	for _, action := range requiredActionNames {
		b.WriteString(fmt.Sprintf("\t%q: {", action))
		for i, arg := range actionRequiredArgs[action] {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(fmt.Sprintf("%q", arg))
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n\n")

	b.WriteString("func ActionOwners(action string) []string {\n")
	b.WriteString("\taction = strings.TrimSpace(action)\n")
	b.WriteString("\towners, ok := builtInActionOwners[action]\n")
	b.WriteString("\tif !ok {\n\t\treturn nil\n\t}\n")
	b.WriteString("\treturn append([]string(nil), owners...)\n")
	b.WriteString("}\n\n")

	b.WriteString("func ActionArgSchema(action string) map[string]string {\n")
	b.WriteString("\treturn builtInActionArgSchemas[action]\n")
	b.WriteString("}\n\n")

	b.WriteString("func ActionRequiredArgs(action string) []string {\n")
	b.WriteString("\treturn builtInActionRequiredArgs[action]\n")
	b.WriteString("}\n\n")

	b.WriteString("func BuiltInActions() []string {\n")
	b.WriteString("\tout := make([]string, 0, len(builtInActionOwners))\n")
	b.WriteString("\tfor action := range builtInActionOwners {\n")
	b.WriteString("\t\tout = append(out, action)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tsort.Strings(out)\n")
	b.WriteString("\treturn out\n")
	b.WriteString("}\n\n")

	b.WriteString("func IsBuiltInAction(action string) bool {\n")
	b.WriteString("\taction = strings.TrimSpace(action)\n")
	b.WriteString("\t_, ok := builtInActionOwners[action]\n")
	b.WriteString("\treturn ok\n")
	b.WriteString("}\n\n")

	b.WriteString("func ValidateBuiltInActionArgs(action string, args map[string]any) error {\n")
	b.WriteString("\taction = strings.TrimSpace(action)\n")
	b.WriteString("\tif !IsBuiltInAction(action) {\n")
	b.WriteString("\t\treturn fmt.Errorf(\"unknown built-in action %q\", action)\n")
	b.WriteString("\t}\n")
	b.WriteString("\tschema := builtInActionArgSchemas[action]\n")
	b.WriteString("\tfor _, required := range builtInActionRequiredArgs[action] {\n")
	b.WriteString("\t\tif _, ok := args[required]; !ok {\n")
	b.WriteString("\t\t\treturn fmt.Errorf(\"action %q requires arg %q\", action, required)\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tfor key, value := range args {\n")
	b.WriteString("\t\texpectedType, ok := schema[key]\n")
	b.WriteString("\t\tif !ok {\n")
	b.WriteString("\t\t\treturn fmt.Errorf(\"action %q does not accept arg %q\", action, key)\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tswitch expectedType {\n")
	b.WriteString("\t\tcase \"bool\":\n")
	b.WriteString("\t\t\tif _, ok := value.(bool); !ok {\n")
	b.WriteString("\t\t\t\treturn fmt.Errorf(\"action %q arg %q expects bool\", action, key)\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\tcase \"string\":\n")
	b.WriteString("\t\t\tif _, ok := value.(string); !ok {\n")
	b.WriteString("\t\t\t\treturn fmt.Errorf(\"action %q arg %q expects string\", action, key)\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\tdefault:\n")
	b.WriteString("\t\t\tif strings.HasPrefix(expectedType, \"enum:\") {\n")
	b.WriteString("\t\t\t\ts, ok := value.(string)\n")
	b.WriteString("\t\t\t\tif !ok {\n")
	b.WriteString("\t\t\t\t\treturn fmt.Errorf(\"action %q arg %q expects string enum\", action, key)\n")
	b.WriteString("\t\t\t\t}\n")
	b.WriteString("\t\t\t\tallowed := strings.Split(strings.TrimPrefix(expectedType, \"enum:\"), \"|\")\n")
	b.WriteString("\t\t\t\tvalid := false\n")
	b.WriteString("\t\t\t\tfor _, item := range allowed {\n")
	b.WriteString("\t\t\t\t\tif s == item {\n")
	b.WriteString("\t\t\t\t\t\tvalid = true\n")
	b.WriteString("\t\t\t\t\t\tbreak\n")
	b.WriteString("\t\t\t\t\t}\n")
	b.WriteString("\t\t\t\t}\n")
	b.WriteString("\t\t\t\tif !valid {\n")
	b.WriteString("\t\t\t\t\treturn fmt.Errorf(\"action %q arg %q invalid value %q (accepted: %s)\", action, key, s, strings.Join(allowed, \", \"))\n")
	b.WriteString("\t\t\t\t}\n")
	b.WriteString("\t\t\t\tcontinue\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t\treturn fmt.Errorf(\"action %q arg %q has unsupported expected type %q\", action, key, expectedType)\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated actionmeta source: %w\n%s", err, b.String())
	}
	return src, nil
}

func collectBindRules(dir string) ([]bindRule, error) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, nil, parser.ParseComments)
	if err != nil {
		return nil, err
	}
	pkg, ok := pkgs["intents"]
	if !ok {
		return nil, fmt.Errorf("intents package not found in %s", dir)
	}

	var paths []string
	for path := range pkg.Files {
		paths = append(paths, path)
	}
	sort.Strings(paths)

	var out []bindRule
	seen := map[string]struct{}{}
	var errs []string

	for _, path := range paths {
		file := pkg.Files[path]
		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.TYPE {
				continue
			}
			for _, spec := range gen.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				doc := ts.Doc
				if doc == nil {
					doc = gen.Doc
				}
				if doc == nil {
					continue
				}
				parsed := parseBindDirectives(doc, ts.Name.Name)
				for _, pr := range parsed {
					for _, e := range pr.Errs {
						errs = append(errs, fmt.Sprintf("%s: %v", filepath.Base(path), e))
					}
					if pr.Rule.Owner == "" || pr.Rule.Action == "" {
						continue
					}
					key := pr.Rule.Owner + "|" + pr.Rule.Action
					if _, ok := seen[key]; ok {
						errs = append(errs, fmt.Sprintf("%s: duplicate binding for scope=%q action=%q", filepath.Base(path), pr.Rule.Owner, pr.Rule.Action))
						continue
					}
					seen[key] = struct{}{}
					out = append(out, pr.Rule)
				}
			}
		}
	}

	if len(errs) > 0 {
		return nil, errors.New(strings.Join(errs, "; "))
	}

	sort.Slice(out, func(i, j int) bool {
		if out[i].Owner != out[j].Owner {
			return out[i].Owner < out[j].Owner
		}
		if out[i].Action != out[j].Action {
			return out[i].Action < out[j].Action
		}
		return out[i].Intent < out[j].Intent
	})
	return out, nil
}

func parseBindDirectives(doc *ast.CommentGroup, intentType string) []parsedRule {
	var out []parsedRule
	for _, c := range doc.List {
		line := strings.TrimSpace(strings.TrimPrefix(c.Text, "//"))
		if !strings.HasPrefix(line, "jjui:bind") {
			continue
		}
		rest := strings.TrimSpace(strings.TrimPrefix(line, "jjui:bind"))
		parts := strings.Fields(rest)
		rule := bindRule{Intent: intentType, Set: map[string]string{}}
		var errs []error

		for _, part := range parts {
			kv := strings.SplitN(part, "=", 2)
			if len(kv) != 2 {
				errs = append(errs, fmt.Errorf("invalid token %q in directive %q", part, line))
				continue
			}
			k := strings.TrimSpace(kv[0])
			v := strings.TrimSpace(kv[1])
			switch k {
			case "scope":
				rule.Owner = v
			case "action":
				rule.Action = v
			case "set":
				for assign := range strings.SplitSeq(v, ",") {
					fv := strings.SplitN(assign, ":", 2)
					if len(fv) != 2 {
						errs = append(errs, fmt.Errorf("invalid set assignment %q in directive %q", assign, line))
						continue
					}
					field := strings.TrimSpace(fv[0])
					value := strings.TrimSpace(fv[1])
					if field == "" || value == "" {
						errs = append(errs, fmt.Errorf("invalid set assignment %q in directive %q", assign, line))
						continue
					}
					if _, exists := rule.Set[field]; exists {
						errs = append(errs, fmt.Errorf("duplicate set field %q in directive %q", field, line))
						continue
					}
					rule.Set[field] = value
				}
			default:
				errs = append(errs, fmt.Errorf("unknown directive key %q in %q", k, line))
			}
		}

		if rule.Owner == "" {
			errs = append(errs, fmt.Errorf("missing scope in directive %q", line))
		}
		if rule.Action == "" {
			errs = append(errs, fmt.Errorf("missing action in directive %q", line))
		}

		out = append(out, parsedRule{Rule: rule, Errs: errs})
	}
	return out
}

func collectIntentTypeMeta(dir string) (map[string]intentTypeMeta, error) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, nil, parser.ParseComments)
	if err != nil {
		return nil, err
	}
	pkg, ok := pkgs["intents"]
	if !ok {
		return nil, fmt.Errorf("intents package not found in %s", dir)
	}

	meta := map[string]intentTypeMeta{}
	for _, file := range pkg.Files {
		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.TYPE {
				continue
			}
			for _, spec := range gen.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				fields := map[string]string{}
				if st, ok := ts.Type.(*ast.StructType); ok {
					for _, f := range st.Fields.List {
						ft := exprTypeName(f.Type)
						for _, n := range f.Names {
							fields[n.Name] = ft
						}
					}
				}
				meta[ts.Name.Name] = intentTypeMeta{Fields: fields}
			}
		}
	}
	return meta, nil
}

func collectEnumTypeMeta(dir string) (map[string][]enumValueMeta, error) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, nil, parser.ParseComments)
	if err != nil {
		return nil, err
	}
	pkg, ok := pkgs["intents"]
	if !ok {
		return nil, fmt.Errorf("intents package not found in %s", dir)
	}

	out := map[string][]enumValueMeta{}
	for _, file := range pkg.Files {
		for _, decl := range file.Decls {
			gen, ok := decl.(*ast.GenDecl)
			if !ok || gen.Tok != token.CONST {
				continue
			}
			var currentType string
			for _, spec := range gen.Specs {
				vs, ok := spec.(*ast.ValueSpec)
				if !ok || len(vs.Names) == 0 {
					continue
				}
				if vs.Type != nil {
					if ident, ok := vs.Type.(*ast.Ident); ok {
						currentType = ident.Name
					} else {
						currentType = ""
					}
				}
				if currentType == "" {
					continue
				}
				for _, name := range vs.Names {
					out[currentType] = append(out[currentType], enumValueMeta{
						ConstName: name.Name,
						Literal:   enumLiteral(currentType, name.Name),
					})
				}
			}
		}
	}
	return out, nil
}

func deriveActionIDs(rules []bindRule) []string {
	seen := map[string]struct{}{}
	actions := make([]string, 0, len(rules))
	for _, rule := range rules {
		fullID := canonicalActionID(rule.Owner, rule.Action)
		if _, ok := seen[fullID]; ok {
			continue
		}
		seen[fullID] = struct{}{}
		actions = append(actions, fullID)
	}
	sort.Strings(actions)
	return actions
}

func deriveActionArgSchemas(rules []bindRule, intents map[string]intentTypeMeta, enums map[string][]enumValueMeta) (map[string]map[string]string, map[string][]string, error) {
	out := map[string]map[string]string{}
	required := map[string]map[string]struct{}{}
	for _, rule := range rules {
		intent, ok := intents[rule.Intent]
		if !ok {
			continue
		}
		for field, value := range rule.Set {
			fieldType, ok := intent.Fields[field]
			if !ok {
				continue
			}
			argName, argType, argRequired, ok := parseArgRef(fieldType, value, enums)
			if !ok {
				continue
			}
			fullID := canonicalActionID(rule.Owner, rule.Action)
			if out[fullID] == nil {
				out[fullID] = map[string]string{}
			}
			if existing, exists := out[fullID][argName]; exists && existing != argType {
				merged, ok := mergeArgTypes(existing, argType)
				if !ok {
					return nil, nil, fmt.Errorf("action %q arg %q has conflicting types %q and %q", fullID, argName, existing, argType)
				}
				out[fullID][argName] = merged
				continue
			}
			out[fullID][argName] = argType
			if argRequired {
				if required[fullID] == nil {
					required[fullID] = map[string]struct{}{}
				}
				required[fullID][argName] = struct{}{}
			}
		}
	}

	requiredOut := map[string][]string{}
	for action, requiredSet := range required {
		args := make([]string, 0, len(requiredSet))
		for arg := range requiredSet {
			args = append(args, arg)
		}
		sort.Strings(args)
		requiredOut[action] = args
	}
	return out, requiredOut, nil
}

func mergeArgTypes(a, b string) (string, bool) {
	if a == b {
		return a, true
	}
	if !strings.HasPrefix(a, "enum:") || !strings.HasPrefix(b, "enum:") {
		return "", false
	}
	seen := map[string]struct{}{}
	var merged []string
	for _, item := range append(strings.Split(strings.TrimPrefix(a, "enum:"), "|"), strings.Split(strings.TrimPrefix(b, "enum:"), "|")...) {
		if item == "" {
			continue
		}
		if _, ok := seen[item]; ok {
			continue
		}
		seen[item] = struct{}{}
		merged = append(merged, item)
	}
	return "enum:" + strings.Join(merged, "|"), true
}

func deriveActionOwners(rules []bindRule) map[string][]string {
	owners := map[string]map[string]struct{}{}
	for _, rule := range rules {
		fullID := canonicalActionID(rule.Owner, rule.Action)
		if owners[fullID] == nil {
			owners[fullID] = map[string]struct{}{}
		}
		owners[fullID][rule.Owner] = struct{}{}
	}

	out := map[string][]string{}
	for action, ownerSet := range owners {
		list := make([]string, 0, len(ownerSet))
		for owner := range ownerSet {
			list = append(list, owner)
		}
		sort.Strings(list)
		out[action] = list
	}
	return out
}

func validateRules(rules []bindRule, intents map[string]intentTypeMeta, enums map[string][]enumValueMeta) error {
	var errs []string
	seenFullIDs := map[string]struct{}{}
	for _, rule := range rules {
		if err := validateOwnerFormat(rule.Owner); err != nil {
			errs = append(errs, fmt.Sprintf("invalid owner %q: %v", rule.Owner, err))
		}
		if err := validateActionFormat(rule.Action); err != nil {
			errs = append(errs, fmt.Sprintf("invalid action %q: %v", rule.Action, err))
		}
		fullID := canonicalActionID(rule.Owner, rule.Action)
		if _, ok := seenFullIDs[fullID]; ok {
			errs = append(errs, fmt.Sprintf("duplicate full action id %q", fullID))
		} else {
			seenFullIDs[fullID] = struct{}{}
		}
		intent, ok := intents[rule.Intent]
		if !ok {
			errs = append(errs, fmt.Sprintf("unknown intent type %q for owner=%q action=%q", rule.Intent, rule.Owner, rule.Action))
			continue
		}
		for field, value := range rule.Set {
			fieldType, ok := intent.Fields[field]
			if !ok {
				errs = append(errs, fmt.Sprintf("unknown field %q on intent %q (owner=%q action=%q)", field, rule.Intent, rule.Owner, rule.Action))
				continue
			}
			if err := validateSetValueType(fieldType, value, enums); err != nil {
				errs = append(errs, fmt.Sprintf("invalid set value for %s.%s (%s): %v", rule.Intent, field, rule.Action, err))
			}
		}
	}
	if len(errs) > 0 {
		return errors.New(strings.Join(errs, "; "))
	}
	return nil
}

func validateOwnerFormat(owner string) error {
	if owner == "" {
		return errors.New("owner is empty")
	}
	segments := strings.SplitSeq(owner, ".")
	for segment := range segments {
		if segment == "" {
			return errors.New("owner has empty segment")
		}
		if !ownerSegmentPattern.MatchString(segment) {
			return fmt.Errorf("owner segment %q must match [a-z0-9_]+", segment)
		}
	}
	return nil
}

func validateActionFormat(action string) error {
	if action == "" {
		return errors.New("action is empty")
	}
	if strings.Contains(action, ".") {
		return errors.New("action cannot contain dots")
	}
	if !actionPattern.MatchString(action) {
		return errors.New("action must match [a-z0-9_]+")
	}
	return nil
}

func canonicalActionID(owner, action string) string {
	return owner + "." + action
}

func validateActionMetadata(actionIDs []string, actionOwners map[string][]string) error {
	var errs []string
	for _, action := range actionIDs {
		if len(actionOwners[action]) == 0 {
			errs = append(errs, fmt.Sprintf("action %q has no owners", action))
		}
	}
	if len(errs) > 0 {
		return errors.New(strings.Join(errs, "; "))
	}
	return nil
}

func validateSetValueType(fieldType, value string, enums map[string][]enumValueMeta) error {
	switch fieldType {
	case "bool":
		if value == "true" || value == "false" || isBoolArg(value) {
			return nil
		}
		return fmt.Errorf("expected bool or $bool(...), got %q", value)
	case "int":
		if _, err := strconv.Atoi(value); err == nil {
			return nil
		}
		return fmt.Errorf("expected int, got %q", value)
	case "string":
		if strings.HasPrefix(value, "\"") && strings.HasSuffix(value, "\"") {
			return nil
		}
		if isStringArg(value) {
			return nil
		}
		return fmt.Errorf("expected quoted string or $string(...), got %q", value)
	default:
		if argName, ok := parseEnumArg(value); ok {
			if len(enums[fieldType]) == 0 {
				return fmt.Errorf("expected identifier for %q, got %q", fieldType, value)
			}
			if strings.TrimSpace(argName) == "" {
				return fmt.Errorf("invalid enum arg %q", value)
			}
			return nil
		}
		if isIdentifier(value) {
			return nil
		}
		return fmt.Errorf("expected identifier for %q, got %q", fieldType, value)
	}
}

func exprTypeName(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		if pkg, ok := t.X.(*ast.Ident); ok {
			return pkg.Name + "." + t.Sel.Name
		}
		return t.Sel.Name
	default:
		return fmt.Sprintf("%T", expr)
	}
}

func isBoolArg(value string) bool {
	return strings.HasPrefix(value, "$bool(") && strings.HasSuffix(value, ")")
}

func isStringArg(value string) bool {
	return strings.HasPrefix(value, "$string(") && strings.HasSuffix(value, ")")
}

func parseArgRef(fieldType, value string, enums map[string][]enumValueMeta) (name string, typ string, required bool, ok bool) {
	if isBoolArg(value) {
		name := strings.TrimSuffix(strings.TrimPrefix(value, "$bool("), ")")
		if name == "" {
			return "", "", false, false
		}
		return name, "bool", false, true
	}
	if argName, ok := parseEnumArg(value); ok {
		if len(enums[fieldType]) == 0 || argName == "" {
			return "", "", false, false
		}
		return argName, enumSchemaForType(fieldType, enums), true, true
	}
	if isStringArg(value) {
		name := strings.TrimSuffix(strings.TrimPrefix(value, "$string("), ")")
		if name == "" {
			return "", "", false, false
		}
		return name, "string", true, true
	}
	return "", "", false, false
}

func parseEnumArg(value string) (string, bool) {
	if strings.HasPrefix(value, "$enum(") && strings.HasSuffix(value, ")") {
		name := strings.TrimSuffix(strings.TrimPrefix(value, "$enum("), ")")
		return strings.TrimSpace(name), true
	}
	return "", false
}

func enumSchemaForType(typeName string, enums map[string][]enumValueMeta) string {
	values := enums[typeName]
	literals := make([]string, 0, len(values))
	for _, value := range values {
		literals = append(literals, value.Literal)
	}
	return "enum:" + strings.Join(literals, "|")
}

func enumLiteral(typeName, constName string) string {
	suffix := strings.TrimPrefix(constName, typeName)
	if suffix == "" {
		suffix = constName
	}
	switch suffix {
	case "Destination":
		return "onto"
	case "Descendants":
		return "source"
	}
	var out []rune
	for i, r := range suffix {
		if unicode.IsUpper(r) && i > 0 {
			out = append(out, '_')
		}
		out = append(out, unicode.ToLower(r))
	}
	return string(out)
}

func sortedEnumTypesUsedByRules(rules []bindRule, intents map[string]intentTypeMeta, enums map[string][]enumValueMeta) []string {
	seen := map[string]struct{}{}
	var out []string
	for _, rule := range rules {
		intent, ok := intents[rule.Intent]
		if !ok {
			continue
		}
		for field, value := range rule.Set {
			if _, ok := parseEnumArg(value); !ok {
				continue
			}
			fieldType := intent.Fields[field]
			if len(enums[fieldType]) == 0 {
				continue
			}
			if _, ok := seen[fieldType]; ok {
				continue
			}
			seen[fieldType] = struct{}{}
			out = append(out, fieldType)
		}
	}
	sort.Strings(out)
	return out
}

func rulesByOwner(rules []bindRule) map[string][]bindRule {
	byOwner := map[string][]bindRule{}
	for _, r := range rules {
		byOwner[r.Owner] = append(byOwner[r.Owner], r)
	}
	for owner := range byOwner {
		sort.Slice(byOwner[owner], func(i, j int) bool {
			return byOwner[owner][i].Action < byOwner[owner][j].Action
		})
	}
	return byOwner
}

func buildIntentExpr(rule bindRule, intents map[string]intentTypeMeta, enums map[string][]enumValueMeta) string {
	if len(rule.Set) == 0 {
		return fmt.Sprintf("intents.%s{}", rule.Intent)
	}
	intent := intents[rule.Intent]
	fields := make([]string, 0, len(rule.Set))
	for field := range rule.Set {
		fields = append(fields, field)
	}
	sort.Strings(fields)
	parts := make([]string, 0, len(fields))
	for _, field := range fields {
		parts = append(parts, fmt.Sprintf("%s: %s", field, renderValue(intent.Fields[field], rule.Set[field], enums)))
	}
	return fmt.Sprintf("intents.%s{%s}", rule.Intent, strings.Join(parts, ", "))
}

func renderValue(fieldType, value string, enums map[string][]enumValueMeta) string {
	if strings.HasPrefix(value, "$bool(") && strings.HasSuffix(value, ")") {
		name := strings.TrimSuffix(strings.TrimPrefix(value, "$bool("), ")")
		return fmt.Sprintf("actionargs.BoolArg(args, %q, false)", name)
	}
	if isStringArg(value) {
		name := strings.TrimSuffix(strings.TrimPrefix(value, "$string("), ")")
		return fmt.Sprintf("actionargs.StringArg(args, %q, \"\")", name)
	}
	if argName, ok := parseEnumArg(value); ok && len(enums[fieldType]) > 0 {
		return fmt.Sprintf("enumArg%s(args, %q)", toCamel(fieldType), argName)
	}
	if value == "true" || value == "false" {
		return value
	}
	if _, err := strconv.Atoi(value); err == nil {
		return value
	}
	if strings.HasPrefix(value, "\"") && strings.HasSuffix(value, "\"") {
		return value
	}
	if isIdentifier(value) {
		return "intents." + value
	}
	panic("unsupported set value: " + value)
}

func rulesUseActionArgs(rules []bindRule) bool {
	for _, rule := range rules {
		for _, value := range rule.Set {
			if strings.HasPrefix(value, "$bool(") && strings.HasSuffix(value, ")") {
				return true
			}
			if isStringArg(value) {
				return true
			}
		}
	}
	return false
}

func isIdentifier(s string) bool {
	if s == "" {
		return false
	}
	for i, r := range s {
		if i == 0 {
			if !(unicode.IsLetter(r) || r == '_') {
				return false
			}
			continue
		}
		if !(unicode.IsLetter(r) || unicode.IsDigit(r) || r == '_') {
			return false
		}
	}
	return true
}

func uniqueOwners(rules []bindRule) []string {
	seen := map[string]struct{}{}
	owners := make([]string, 0, len(rules))
	for _, r := range rules {
		if _, ok := seen[r.Owner]; ok {
			continue
		}
		seen[r.Owner] = struct{}{}
		owners = append(owners, r.Owner)
	}
	sort.Strings(owners)
	return owners
}

func revisionsOwnerList(owners []string) []string {
	out := make([]string, 0, len(owners))
	for _, owner := range owners {
		if isRevisionsOwner(owner) {
			out = append(out, owner)
		}
	}
	sort.Strings(out)
	return out
}

func isRevisionsOwner(owner string) bool {
	switch owner {
	case "bookmarks", "choose", "diff", "file_search", "flash", "git", "input", "oplog", "password", "redo", "revset", "status.input", "ui", "ui.preview", "undo":
		return false
	}
	return true
}

func ownerConst(owner string) string {
	parts := strings.Split(owner, ".")
	if len(parts) > 1 && parts[0] == "revisions" {
		parts = parts[1:]
	}
	for i := range parts {
		parts[i] = toCamel(parts[i])
	}
	return "Owner" + strings.Join(parts, "")
}

func toCamel(s string) string {
	s = filepath.Base(s)
	parts := strings.Split(s, "_")
	for i := range parts {
		if parts[i] == "" {
			continue
		}
		parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
	}
	return strings.Join(parts, "")
}

// Hand-written Lua API stubs that cannot be derived from annotations.
const luaHandWrittenAPI = `---@class jjui.revisions
---@field current fun(): string? Get the current selected revision's change ID
---@field checked fun(): string[] Get array of checked revision change IDs
---@field refresh fun(options?: {keep_selections?: boolean, selected_revision?: string}) Refresh revisions
---@field navigate fun(options?: {target?: "parent"|"child"|"children"|"working"|"working_copy"|"work", by?: integer, page?: boolean, to?: string, fallback?: string, ensureView?: boolean, allowStream?: boolean}) Navigate revisions

---@class jjui.revset
---@field current fun(): string Get current revset string
---@field default fun(): string Get default revset string

---@class jjui.context
---@field change_id fun(): string? Get selected item's change ID
---@field commit_id fun(): string? Get selected item's commit ID
---@field file fun(): string? Get selected file path
---@field operation_id fun(): string? Get selected operation ID
---@field checked_files fun(): string[] Get array of checked files
---@field checked_change_ids fun(): string[] Get array of checked change IDs
---@field checked_commit_ids fun(): string[] Get array of checked commit IDs

---Run a jj command asynchronously (yields, resumes after completion)
---@param ... string|string[] Command arguments for jj (variadic strings or a single table)
---@return string output The command output
function jj_async(...) end

---Run a jj command interactively (takes over the terminal)
---@param ... string|string[] Command arguments for jj (variadic strings or a single table)
function jj_interactive(...) end

---Run a jj command synchronously and return its output
---@param ... string|string[] Command arguments for jj (variadic strings or a single table)
---@return string? output The command output (nil on error)
---@return string? error The error message (nil on success)
function jj(...) end

---Show a flash message in the status bar
---@param text_or_options string|{text: string, error?: boolean, sticky?: boolean} Message text or options table
function flash(text_or_options) end

---Copy text to the system clipboard
---@param text string Text to copy
function copy_to_clipboard(text) end

---Execute a shell command
---@param command string Shell command to execute
---@return string output The command output
function exec_shell(command) end

---Split text into an array of lines
---@param text string Text to split
---@param keepEmpty? boolean Keep empty lines (default: false)
---@return string[] lines Array of lines
function split_lines(text, keepEmpty) end

---Show a choice dialog and wait for user selection (yields)
---@param options_or_array string[]|{options: string[], title?: string, filter?: boolean, ordered?: boolean} Options array or options table
---@return string|nil selected The selected option, or nil if cancelled
function choose(options_or_array) end

---Show a text input dialog and wait for user input (yields)
---@param options {title?: string, prompt?: string} Input options
---@return string|nil value The entered text, or nil if cancelled
function input(options) end

---Yield and wait for the current view to close
function wait_close() end

---Yield and wait for revisions to be updated
function wait_refresh() end
`

type ownerNode struct {
	name     string
	children map[string]*ownerNode
	actions  []string // action tokens (last segment of canonical action ID)
}

func generateLuaTypesSource(actionIDs []string, argSchemas map[string]map[string]string, requiredArgs map[string][]string, owners map[string][]string) ([]byte, error) {
	// Build owner tree from action IDs and their owners
	root := &ownerNode{children: map[string]*ownerNode{}}
	actionsByOwner := map[string][]string{} // owner -> list of canonical action IDs

	for _, actionID := range actionIDs {
		ownerList := owners[actionID]
		for _, owner := range ownerList {
			actionsByOwner[owner] = append(actionsByOwner[owner], actionID)
		}
	}

	// Collect all unique owner strings and build tree
	allOwners := make([]string, 0, len(actionsByOwner))
	for owner := range actionsByOwner {
		allOwners = append(allOwners, owner)
	}
	sort.Strings(allOwners)

	for _, owner := range allOwners {
		segments := strings.Split(owner, ".")
		current := root
		for _, seg := range segments {
			if current.children[seg] == nil {
				current.children[seg] = &ownerNode{name: seg, children: map[string]*ownerNode{}}
			}
			current = current.children[seg]
		}
	}

	var b bytes.Buffer
	b.WriteString("---@meta\n")
	b.WriteString("-- LuaLS type definitions for jjui Lua API\n")
	b.WriteString("-- Code generated by cmd/genactions; DO NOT EDIT.\n\n")

	// Hand-written API stubs
	b.WriteString(luaHandWrittenAPI)
	b.WriteString("\n")

	// Generate action classes for each owner
	for _, owner := range allOwners {
		className := "jjui." + owner
		b.WriteString(fmt.Sprintf("---@class %s\n", className))

		// Add child fields
		childNames := sortedChildNames(root, owner)
		for _, childName := range childNames {
			childOwner := owner + "." + childName
			b.WriteString(fmt.Sprintf("---@field %s jjui.%s\n", childName, childOwner))
		}

		// Add action functions
		actions := actionsByOwner[owner]
		sort.Strings(actions)
		hasCancel := false
		hasClose := false
		for _, actionID := range actions {
			token := actionTokenFromCanonical(actionID)
			if token == "" {
				continue
			}
			if token == "cancel" {
				hasCancel = true
			}
			if token == "close" {
				hasClose = true
			}
			schema := argSchemas[actionID]
			required := requiredArgs[actionID]
			writeActionFunction(&b, token, schema, required)
		}
		// Mirror the runtime "close" alias for "cancel"
		if hasCancel && !hasClose {
			b.WriteString("---@field close fun()\n")
		}
		b.WriteString("\n")
	}

	// Root jjui class
	b.WriteString("---@class jjui\n")
	b.WriteString("---@field revisions jjui.revisions\n")
	b.WriteString("---@field revset jjui.revset\n")
	b.WriteString("---@field context jjui.context\n")

	// Add top-level owner children (those without dots)
	topLevel := sortedKeys(root.children)
	for _, name := range topLevel {
		// Skip revisions, revset, context — already declared above with hand-written types
		if name == "revisions" || name == "revset" || name == "context" {
			continue
		}
		b.WriteString(fmt.Sprintf("---@field %s jjui.%s\n", name, name))
	}

	b.WriteString("---@field builtin jjui.builtin\n")

	// Write hand-written function fields on jjui
	b.WriteString("---@field jj_async fun(...: string|string[]): string\n")
	b.WriteString("---@field jj_interactive fun(...: string|string[])\n")
	b.WriteString("---@field jj fun(...: string|string[]): string?, string?\n")
	b.WriteString("---@field flash fun(text_or_options: string|{text: string, error?: boolean, sticky?: boolean})\n")
	b.WriteString("---@field copy_to_clipboard fun(text: string)\n")
	b.WriteString("---@field exec_shell fun(command: string): string\n")
	b.WriteString("---@field split_lines fun(text: string, keepEmpty?: boolean): string[]\n")
	b.WriteString("---@field choose fun(options_or_array: string[]|{options: string[], title?: string, filter?: boolean, ordered?: boolean}): string|nil\n")
	b.WriteString("---@field input fun(options: {title?: string, prompt?: string}): string|nil\n")
	b.WriteString("---@field wait_close fun()\n")
	b.WriteString("---@field wait_refresh fun()\n")
	b.WriteString("\n")

	// jjui.builtin class — mirrors the generated action structure
	b.WriteString("---@class jjui.builtin\n")
	for _, name := range topLevel {
		b.WriteString(fmt.Sprintf("---@field %s jjui.%s\n", name, name))
	}
	b.WriteString("\n")

	// Global aliases
	b.WriteString("---@type jjui\n")
	b.WriteString("jjui = {}\n\n")

	b.WriteString("---@type jjui.revisions\n")
	b.WriteString("revisions = {}\n\n")

	b.WriteString("---@type jjui.revset\n")
	b.WriteString("revset = {}\n\n")

	b.WriteString("---@type jjui.context\n")
	b.WriteString("context = {}\n\n")

	// Expose diff and ui as globals if they exist as top-level owners
	for _, name := range topLevel {
		if name == "diff" || name == "ui" {
			b.WriteString(fmt.Sprintf("---@type jjui.%s\n", name))
			b.WriteString(fmt.Sprintf("%s = {}\n\n", name))
		}
	}

	return b.Bytes(), nil
}

func sortedChildNames(root *ownerNode, owner string) []string {
	segments := strings.Split(owner, ".")
	current := root
	for _, seg := range segments {
		child, ok := current.children[seg]
		if !ok {
			return nil
		}
		current = child
	}
	return sortedKeys(current.children)
}

func sortedKeys(m map[string]*ownerNode) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func actionTokenFromCanonical(canonical string) string {
	idx := strings.LastIndex(canonical, ".")
	if idx < 0 {
		return canonical
	}
	return canonical[idx+1:]
}

func writeActionFunction(b *bytes.Buffer, token string, schema map[string]string, required []string) {
	if len(schema) == 0 {
		b.WriteString(fmt.Sprintf("---@field %s fun()\n", token))
		return
	}

	// Check for single required string arg (supports positional call)
	requiredSet := map[string]struct{}{}
	for _, r := range required {
		requiredSet[r] = struct{}{}
	}

	hasSingleRequiredString := len(required) == 1 && schema[required[0]] == "string"

	// Build args type annotation
	argNames := make([]string, 0, len(schema))
	for name := range schema {
		argNames = append(argNames, name)
	}
	sort.Strings(argNames)

	var params []string
	for _, name := range argNames {
		typ := schema[name]
		_, isRequired := requiredSet[name]
		luaType := schemaTypeToLua(typ)
		optional := ""
		if !isRequired {
			optional = "?"
		}
		params = append(params, fmt.Sprintf("%s%s: %s", name, optional, luaType))
	}

	if hasSingleRequiredString {
		// Can be called with just the string value or a table
		b.WriteString(fmt.Sprintf("---@field %s fun(value?: string|{%s})\n", token, strings.Join(params, ", ")))
	} else {
		b.WriteString(fmt.Sprintf("---@field %s fun(args: {%s})\n", token, strings.Join(params, ", ")))
	}
}

func schemaTypeToLua(schemaType string) string {
	switch schemaType {
	case "bool":
		return "boolean"
	case "string":
		return "string"
	default:
		if strings.HasPrefix(schemaType, "enum:") {
			values := strings.Split(strings.TrimPrefix(schemaType, "enum:"), "|")
			quoted := make([]string, len(values))
			for i, v := range values {
				quoted[i] = fmt.Sprintf("%q", v)
			}
			return strings.Join(quoted, "|")
		}
		return "any"
	}
}
